# Fly.io configuration for Cyberpunk App
app = 'cyberpunk-app'
primary_region = 'iad'
console_command = '/bin/sh'

[build]
dockerfile = 'Dockerfile'
target = 'production'

[env]
NODE_ENV = 'production'
PORT = '3000'
HOSTNAME = '0.0.0.0'

[experimental]
auto_rollback = true

[[services]]
protocol = 'tcp'
internal_port = 3000
processes = ['app']

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
type = 'connections'
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = '15s'
timeout = '2s'
grace_period = '1s'

[[services.http_checks]]
interval = '10s'
timeout = '2s'
grace_period = '1s'
method = 'get'
path = '/api/health'
protocol = 'http'
tls_skip_verify = false

[services.http_checks.headers]
Content-Type = 'application/json'

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512

[metrics]
port = 9091
path = "/metrics"