services:
  - type: web
    name: cyberpunk-app
    runtime: docker
    plan: free
    repo: https://github.com/alexobedeanu/web-app.git # Înlocuiește cu repo-ul tău
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: node server.js
    region: oregon
    buildCommand: ""
    startCommand: "sh -c 'npx prisma migrate deploy && node server.js'"
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false