apiVersion: v1
kind: Service
metadata:
  name: cyberpunk-app
  labels:
    app: cyberpunk-app
spec:
  build:
    type: dockerfile
    dockerfile: Dockerfile
  
  deployment:
    replicas: 1
    
  resources:
    cpu: 256m
    memory: 512Mi
    
  ports:
    - port: 3000
      protocol: TCP
      
  env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"
    - name: HOSTNAME
      value: "0.0.0.0"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: url
    - name: NEXTAUTH_SECRET
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: secret
    - name: NEXTAUTH_URL
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: url
    - name: GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: google-secret
          key: client-id
    - name: GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: google-secret
          key: client-secret
          
  health:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10